const BREAKPOINTS = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  '2xl': 1536,
} as const

const Z_INDEX = {
  base: 0,
  dropdown: 1000,
  sticky: 1100,
  sidebar: 1200,
  overlay: 1300,
  modal: 1400,
  popover: 1500,
  tooltip: 1600,
  toast: 1700,
} as const

const config = {
  darkMode: 'class',
  theme: {
    screens: {
      xs: '320px',
      sm: `${BREAKPOINTS.sm}px`,
      md: `${BREAKPOINTS.md}px`,
      lg: `${BREAKPOINTS.lg}px`,
      xl: `${BREAKPOINTS.xl}px`,
      '2xl': `${BREAKPOINTS['2xl']}px`,
      '3xl': '1920px',
      '4xl': '2560px',
    },
    extend: {
      fontFamily: {
        sans: [
          'var(--font-sans)',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'sans-serif',
        ],
        serif: ['var(--font-serif)', 'Georgia', 'Cambria', 'serif'],
        mono: [
          'var(--font-mono)',
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          'monospace',
        ],
        terminal: ['var(--font-mono)', 'ui-monospace', 'monospace'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-conic': 'conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))',
        // Premium Gradient Utilities
        'gradient-premium': 'linear-gradient(135deg, var(--tw-gradient-stops))',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
        // Premium Border Utilities
        '4xl': '2rem',
        '5xl': '2.5rem',
        // MiniMax Border Radius Tokens
        pill: '9999px',
        comfortable: '13px',
        generous: '20px',
        large: '24px',
      },
      fontSize: {
        display: ['4rem', { lineHeight: '0.95', letterSpacing: '-0.055em' }],
        h1: ['3rem', { lineHeight: '0.98', letterSpacing: '-0.045em' }],
        h2: ['2.25rem', { lineHeight: '1.02', letterSpacing: '-0.035em' }],
        h3: ['1.5rem', { lineHeight: '1.15', letterSpacing: '-0.025em' }],
        h4: ['1.125rem', { lineHeight: '1.3', letterSpacing: '-0.015em' }],
        'body-lg': ['1.0625rem', { lineHeight: '1.75', letterSpacing: '-0.01em' }],
        'body-sm': ['0.8125rem', { lineHeight: '1.6', letterSpacing: '0' }],
        label: ['0.75rem', { lineHeight: '1.2', letterSpacing: '0.12em' }],
        overline: ['0.6875rem', { lineHeight: '1.2', letterSpacing: '0.18em' }],
        'fluid-xs': 'clamp(0.75rem, 0.7rem + 0.25vw, 0.8125rem)',
        'fluid-sm': 'clamp(0.875rem, 0.8rem + 0.375vw, 0.9375rem)',
        'fluid-base': 'clamp(1rem, 0.95rem + 0.25vw, 1.0625rem)',
        'fluid-lg': 'clamp(1.125rem, 1.05rem + 0.375vw, 1.25rem)',
        'fluid-xl': 'clamp(1.25rem, 1.15rem + 0.5vw, 1.5rem)',
        'fluid-2xl': 'clamp(1.5rem, 1.35rem + 0.75vw, 2rem)',
        'fluid-3xl': 'clamp(1.875rem, 1.65rem + 1.125vw, 2.5rem)',
        'fluid-4xl': 'clamp(2.25rem, 1.95rem + 1.5vw, 3.25rem)',
        'fluid-5xl': 'clamp(3rem, 2.5rem + 2.5vw, 5rem)',
        'fluid-6xl': 'clamp(3.75rem, 3.125rem + 3.125vw, 6.25rem)',
        'fluid-7xl': 'clamp(4.5rem, 3.75rem + 3.75vw, 7.5rem)',
        'fluid-8xl': 'clamp(6rem, 5rem + 5vw, 10rem)',
        'fluid-9xl': 'clamp(7.5rem, 6.25rem + 6.25vw, 12.5rem)',
        '2xs': '0.625rem',
        xs: '0.75rem',
        sm: '0.8125rem',
        base: '0.875rem',
        caption: '0.8125rem',
        body: '0.9375rem',
        subhead: '1.0625rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': ['1.5rem', { lineHeight: '2rem' }],
        '3xl': ['1.875rem', { lineHeight: '2.25rem' }],
        '4xl': ['2.25rem', { lineHeight: '2.5rem' }],
        '5xl': ['3rem', { lineHeight: '1' }],
      },
      spacing: {
        'fluid-3xs': 'clamp(0.25rem, 0.2rem + 0.25vw, 0.5rem)',
        'fluid-2xs': 'clamp(0.5rem, 0.4rem + 0.5vw, 0.75rem)',
        'fluid-xs': 'clamp(0.75rem, 0.6rem + 0.75vw, 1rem)',
        'fluid-sm': 'clamp(1rem, 0.85rem + 0.75vw, 1.5rem)',
        'fluid-md': 'clamp(1.5rem, 1.25rem + 1.25vw, 2.5rem)',
        'fluid-lg': 'clamp(2rem, 1.75rem + 1.25vw, 3.5rem)',
        'fluid-xl': 'clamp(3rem, 2.5rem + 2.5vw, 5rem)',
        'fluid-2xl': 'clamp(4rem, 3.5rem + 2.5vw, 7rem)',
        'fluid-3xl': 'clamp(5rem, 4.5rem + 2.5vw, 10rem)',
        '18': '4.5rem',
        '128': '32rem',
        // Enhanced Spacing - subtle gap variations
        '4.5': '1.125rem',
        '5.5': '1.375rem',
        '6.5': '1.625rem',
        '7.5': '1.875rem',
        '8.5': '2.125rem',
        '9.5': '2.375rem',
        '10.5': '2.625rem',
        '11.5': '2.875rem',
        '12.5': '3.125rem',
        '13.5': '3.375rem',
        '14.5': '3.625rem',
        '15.5': '3.875rem',
        '16.5': '4.125rem',
        '17.5': '4.375rem',
        '18.5': '4.625rem',
        '19.5': '4.875rem',
        '20.5': '5.125rem',
        '21.5': '5.375rem',
        '22.5': '5.625rem',
        '23.5': '5.875rem',
        '24.5': '6.125rem',
        // Safe area spacing (used via utility classes in CSS, added here for token completeness)
        'safe-bottom': 'env(safe-area-inset-bottom, 0px)',
        'safe-top': 'env(safe-area-inset-top, 0px)',
        'safe-left': 'env(safe-area-inset-left, 0px)',
        'safe-right': 'env(safe-area-inset-right, 0px)',
      },
      maxWidth: {
        xs: '20rem',
        'container-xs': '320px',
        'container-sm': '480px',
        'container-md': '768px',
        'container-lg': '1024px',
        'container-xl': '1200px',
        'container-2xl': '1440px',
        'container-3xl': '1920px',
        'container-4xl': '2560px',
      },
      zIndex: {
        '60': '60',
        '70': '70',
        '80': '80',
        '90': '90',
        '100': '100',
        '9999': '9999',
        ...Object.fromEntries(Object.entries(Z_INDEX).map(([key, value]) => [key, String(value)])),
      },
      // Shadow Utilities
      boxShadow: {
        'glow-primary': '0 0 20px color-mix(in srgb, var(--primary) 30%, transparent), 0 0 40px color-mix(in srgb, var(--primary) 20%, transparent)',
      },
      // Transition utilities (custom timing handled via inline styles)
      // Animation delays (handled via inline styles)
      colors: {
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: {
          DEFAULT: 'var(--card)',
          foreground: 'var(--card-foreground)',
        },
        popover: {
          DEFAULT: 'var(--popover)',
          foreground: 'var(--popover-foreground)',
        },
        primary: {
          DEFAULT: 'var(--primary)',
          foreground: 'var(--primary-foreground)',
        },
        secondary: {
          DEFAULT: 'var(--secondary)',
          foreground: 'var(--secondary-foreground)',
        },
        muted: {
          DEFAULT: 'var(--muted)',
          foreground: 'var(--muted-foreground)',
        },
        accent: {
          DEFAULT: 'var(--accent)',
          foreground: 'var(--accent-foreground)',
        },
        success: {
          DEFAULT: 'var(--success)',
          foreground: 'var(--success-foreground)',
        },
        warning: {
          DEFAULT: 'var(--warning)',
          foreground: 'var(--warning-foreground)',
        },
        destructive: {
          DEFAULT: 'var(--destructive)',
          foreground: 'var(--destructive-foreground)',
        },
        border: 'var(--border)',
        input: 'var(--input)',
        ring: 'var(--ring)',
        chart: {
          '1': 'var(--chart-1)',
          '2': 'var(--chart-2)',
          '3': 'var(--chart-3)',
          '4': 'var(--chart-4)',
          '5': 'var(--chart-5)',
        },
        sidebar: {
          DEFAULT: 'var(--sidebar-background)',
          foreground: 'var(--sidebar-foreground)',
          primary: 'var(--sidebar-primary)',
          'primary-foreground': 'var(--sidebar-primary-foreground)',
          accent: 'var(--sidebar-accent)',
          'accent-foreground': 'var(--sidebar-accent-foreground)',
          border: 'var(--sidebar-border)',
          ring: 'var(--sidebar-ring)',
        },
        /* Secondary accent - blue tint */
        rose: {
          DEFAULT: 'hsl(210 100% 40%)',
          50: '210 100% 95%',
          100: '210 100% 90%',
          200: '210 100% 82%',
          300: '210 100% 74%',
          400: '210 100% 66%',
          500: '210 100% 58%',
          600: '210 100% 50%',
          700: '210 100% 42%',
          800: '210 100% 34%',
          900: '210 100% 26%',
        },
        /* Tertiary accent - teal tint */
        bronze: {
          DEFAULT: 'hsl(190 80% 38%)',
          50: '190 60% 92%',
          100: '190 60% 86%',
          200: '190 60% 78%',
          300: '190 60% 70%',
          400: '190 60% 62%',
          500: '190 60% 56%',
          600: '190 60% 48%',
          700: '190 60% 40%',
          800: '190 60% 32%',
          900: '190 60% 24%',
        },
        gray: {
          50: 'hsl(var(--legacy-50))',
          100: 'hsl(var(--legacy-100))',
          200: 'hsl(var(--legacy-100))',
          300: 'hsl(var(--legacy-300))',
          400: 'hsl(var(--legacy-400))',
          500: 'hsl(var(--legacy-500))',
          600: 'hsl(var(--legacy-600))',
          700: 'hsl(var(--legacy-700))',
          800: 'hsl(var(--legacy-800))',
          900: 'hsl(var(--legacy-900))',
          950: 'hsl(var(--legacy-950))',
        },
        zinc: {
          50: 'hsl(var(--legacy-50))',
          100: 'hsl(var(--legacy-100))',
          200: 'hsl(var(--legacy-100))',
          300: 'hsl(var(--legacy-100))',
          400: 'hsl(var(--legacy-400))',
          500: 'hsl(var(--legacy-500))',
          600: 'hsl(var(--legacy-600))',
          700: 'hsl(var(--legacy-700))',
          800: 'hsl(var(--legacy-800))',
          900: 'hsl(var(--legacy-900))',
          950: 'hsl(var(--legacy-950))',
        },
        neutral: {
          50: 'hsl(var(--legacy-50))',
          100: 'hsl(var(--legacy-100))',
          200: 'hsl(var(--legacy-100))',
          300: 'hsl(var(--legacy-300))',
          400: 'hsl(var(--legacy-400))',
          500: 'hsl(var(--legacy-500))',
          600: 'hsl(var(--legacy-600))',
          700: 'hsl(var(--legacy-700))',
          800: 'hsl(var(--legacy-800))',
          900: 'hsl(var(--legacy-900))',
          950: 'hsl(var(--legacy-950))',
        },
        slate: {
          50: 'hsl(var(--legacy-50))',
          100: 'hsl(var(--legacy-100))',
          200: 'hsl(var(--legacy-100))',
          300: 'hsl(var(--legacy-300))',
          400: 'hsl(var(--legacy-400))',
          500: 'hsl(var(--legacy-500))',
          600: 'hsl(var(--legacy-600))',
          700: 'hsl(var(--legacy-700))',
          800: 'hsl(var(--legacy-800))',
          900: 'hsl(var(--legacy-900))',
          950: 'hsl(var(--legacy-950))',
        },
        stone: {
          50: 'hsl(var(--legacy-50))',
          100: 'hsl(var(--legacy-50))',
          200: 'hsl(var(--legacy-50))',
          300: 'hsl(var(--legacy-50))',
          400: 'hsl(var(--legacy-500))',
          500: 'hsl(var(--legacy-500))',
          600: 'hsl(var(--legacy-600))',
          700: 'hsl(var(--legacy-700))',
          800: 'hsl(var(--legacy-800))',
          900: 'hsl(var(--legacy-900))',
          950: 'hsl(var(--legacy-950))',
        },
        white: 'hsl(var(--legacy-white))',
        black: 'hsl(var(--legacy-black))',
        matte: {
          obsidian: 'hsl(var(--legacy-black))',
          panel: 'hsl(var(--precision-panel))',
          layer: 'hsl(var(--precision-panel-line))',
          line: 'hsl(var(--precision-panel-line))',
        },
        precision: {
          cobalt: 'var(--primary)',
          highlight: 'var(--foreground)',
          line: 'color-mix(in srgb, var(--primary) 6%, transparent)',
        },
        'precision-blue': 'var(--primary)',
        'steel-grey': 'var(--muted-foreground)',
        'cyber-pink': 'hsl(210 100% 40%)',
        'matte-black': 'hsl(var(--legacy-black))',
        obsidian: 'var(--background)',
        // macOS Native Brand Colors
        minimax: {
          brand: 'var(--primary)',
          pink: 'hsl(340 75% 55%)',
          sky: 'hsl(203 100% 42%)',
          deep: 'hsl(210 100% 40%)',
        },
        semantic: {
          success: 'hsl(var(--semantic-success))',
          'success-fg': 'hsl(var(--semantic-success-fg))',
          'success-bg': 'hsl(var(--semantic-success-bg))',
          'success-border': 'hsl(var(--semantic-success-border))',
          warning: 'hsl(var(--semantic-warning))',
          'warning-fg': 'hsl(var(--semantic-warning-fg))',
          'warning-bg': 'hsl(var(--semantic-warning-bg))',
          'warning-border': 'hsl(var(--semantic-warning-border))',
          error: 'hsl(var(--semantic-error))',
          'error-fg': 'hsl(var(--semantic-error-fg))',
          'error-bg': 'hsl(var(--semantic-error-bg))',
          'error-border': 'hsl(var(--semantic-error-border))',
          info: 'hsl(var(--semantic-info))',
          'info-fg': 'hsl(var(--semantic-info-fg))',
          'info-bg': 'hsl(var(--semantic-info-bg))',
          'info-border': 'hsl(var(--semantic-info-border))',
        },
      },
      keyframes: {
        'accordion-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-accordion-content-height)',
          },
        },
        'accordion-up': {
          from: {
            height: 'var(--radix-accordion-content-height)',
          },
          to: {
            height: '0',
          },
        },
        'collapsible-down': {
          from: {
            height: '0',
          },
          to: {
            height: 'var(--radix-collapsible-content-height)',
          },
        },
        'collapsible-up': {
          from: {
            height: 'var(--radix-collapsible-content-height)',
          },
          to: {
            height: '0',
          },
        },
        'scanner-smooth': {
          '0%': {
            top: '0%',
          },
          '50%': {
            top: 'calc(100% - 3px)',
          },
          '50.001%': {
            top: 'calc(100% - 3px)',
          },
          '100%': {
            top: '0%',
          },
        },
        'success-pulse': {
          '0%': {
            opacity: '0',
          },
          '50%': {
            opacity: '1',
          },
          '100%': {
            opacity: '0',
          },
        },
        'success-sweep': {
          '0%': {
            transform: 'translateX(-100%)',
          },
          '100%': {
            transform: 'translateX(100%)',
          },
        },
        shimmer: {
          '0%': {
            backgroundPosition: '-200% 0',
          },
          '100%': {
            backgroundPosition: '200% 0',
          },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'collapsible-down': 'collapsible-down 0.2s ease-out',
        'collapsible-up': 'collapsible-up 0.2s ease-out',
        'scanner-smooth': 'scanner-smooth 8s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'success-pulse': 'success-pulse 3s ease-in-out infinite',
        'success-sweep': 'success-sweep 1.5s ease-in-out forwards',
        shimmer: 'shimmer 2s linear infinite',
      },
      typography: {
        DEFAULT: {
          css: {
            'code::before': {
              content: '""',
            },
            'code::after': {
              content: '""',
            },
            table: {
              width: '100%',
              marginTop: '1.5rem',
              marginBottom: '1.5rem',
              borderCollapse: 'collapse',
              fontSize: '0.875rem',
              lineHeight: '1.25rem',
              border: '1px solid var(--tw-prose-td-borders)',
            },
            thead: {
              backgroundColor: 'var(--tw-prose-th-borders)',
              borderWidth: '1px',
              borderStyle: 'solid',
              borderColor: 'var(--tw-prose-td-borders)',
            },
            'thead th': {
              padding: '1rem',
              fontWeight: '500',
              textAlign: 'left',
              backgroundColor: 'var(--tw-prose-th-borders)',
            },
            'tbody tr': {
              borderBottomWeight: '1px',
              borderBottomStyle: 'solid',
              borderBottomColor: 'var(--tw-prose-td-borders)',
            },
            'tbody td': {
              padding: '1rem',
              borderWidth: '1px',
              borderStyle: 'solid',
              borderColor: 'var(--tw-prose-td-borders)',
            },
          },
        },
      },
    },
  },
}
export default config
